#!/bin/bash

files=(
    "/var/mobile/Library/Preferences/bag.xml.tuberepairpreference.plist"
    "/path/to/another/file.jpg"
)

for file in "${files[@]}"; do
    if [ -f "$file" ]; then
        echo "Clearing previous settings."
        rm -f "$file"
    else
        echo "Error."
    fi
done

echo "Initialization done!"
